In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'd:\\workspace\\MRes'

In [3]:
df = pd.read_csv("datasets\mimic-cxr-jpg-2.1.0\mimic-cxr-2.0.0-metadata.csv.gz")

In [4]:
result = df[df['dicom_id'] == '687754ce-7420bfd3-0a19911f-a27a3916-9019cd53']
result

,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning
1461,687754ce-7420bfd3-0a19911f-a27a3916-9019cd53,10032725,50331901,CHEST (PORTABLE AP),NaN,2140,1760,21430322,101701.0,CHEST (PORTABLE AP),NaN,NaN

In [5]:
df.loc[df['ViewPosition'].isna()]

,dicom_id,subject_id,study_id,PerformedProcedureStepDescription,ViewPosition,Rows,Columns,StudyDate,StudyTime,ProcedureCodeSequence_CodeMeaning,ViewCodeSequence_CodeMeaning,PatientOrientationCodeSequence_CodeMeaning
44,8039752c-2ea661b7-16f1eafe-055b7e7b-dbd4cdd1,10001122,53447138,CHEST (PA AND LAT),NaN,2140,1760,21431210,162003.0,CHEST (PA AND LAT),NaN,NaN
45,832b57d8-3ae08663-e152699e-51c5db98-b7cb4226,10001122,53447138,CHEST (PA AND LAT),NaN,2140,1760,21431210,162003.0,CHEST (PA AND LAT),NaN,NaN
130,227844e4-4cf4b717-bb4bf0e5-961883ef-664990fe,10002013,55312734,CHEST (PA AND LAT),NaN,2140,1760,21601005,164810.0,CHEST (PA AND LAT),NaN,NaN
131,66ccec51-f0d48809-dc6f7ba3-68acf728-a1514edf,10002013,55312734,CHEST (PA AND LAT),NaN,2140,1760,21601005,164810.0,CHEST (PA AND LAT),NaN,NaN
145,8b88f03a-2004113d-4118def5-35820db5-d0913df8,10002221,53781756,CHEST (PA AND LAT),NaN,2140,1760,22001221,153523.0,CHEST (PA AND LAT),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
377085,458b41b5-6c8bfc44-a4dff92c-254519d0-9c40e805,19999068,59937395,CHEST (PORTABLE AP),NaN,2140,1760,21610825,112914.0,CHEST (PORTABLE AP),NaN,NaN
377088,9c44a9e5-7a8fcfa1-cb6b451f-1d1ac993-5312b1c2,19999270,55274188,CHEST (PA AND LAT),NaN,2140,1760,21821112,104527.0,CHEST (PA AND LAT),NaN,NaN
377089,f5cbd087-0490844c-4e1d38f7-154dc31a-4e99dbd1,19999270,55274188,CHEST (PA AND LAT),NaN,2140,1760,21821112,104527.0,CHEST (PA AND LAT),NaN,NaN
377090,bf6e3bdb-4ec92b48-340d4e48-7a00234a-1b76dae7,19999270,56267753,CHEST (PA AND LAT),NaN,2140,1760,21831203,135727.0,CHEST (PA AND LAT),NaN,NaN
377091,f83a9135-334e26ff-6419b6b9-1457634a-aaed76a3,19999270,56267753,CHEST (PA AND LAT),NaN,2140,1760,21831203,135727.0,CHEST (PA AND LAT),NaN,NaN

In [12]:
(df['ViewPosition']=='LATERAL').mean()+df['ViewPosition'].isna().mean()

0.26152051125666254

In [19]:
(df['ViewPosition']=='PA').mean()+(df['ViewPosition']=='AP').mean()+(df['ViewPosition']=='AP AXIAL').mean()

0.6452653072047944

In [13]:
gt = pd.read_csv("./datasets/mimic-cxr-clean/gt/metadata.csv")

In [21]:
(gt['ViewPosition']=='AP').mean()+(gt['ViewPosition']=='PA').mean()

0.6569484936831875

In [17]:
(gt['ViewPosition'].isna()).mean()+(gt['ViewPosition']=='LATERAL').mean()

0.22546161321671526

In [18]:
df['ViewPosition'].unique()

array(['PA', 'LATERAL', 'AP', 'LL', nan, 'LAO', 'RAO', 'AP AXIAL',
       'SWIMMERS', 'PA LLD', 'AP LLD', 'XTABLE LATERAL', 'AP RLD',
       'PA RLD', 'LPO'], dtype=object)